var MONACO_THEME_DARK = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'delimiter.xml',         foreground: '4a6080' },
    { token: 'metatag.xml',           foreground: 'f472b6' },

    { token: 'tag',                   foreground: '56b6c2', fontStyle: 'bold' },
    { token: 'tag.id.pug',            foreground: '56b6c2' },
    { token: 'attribute.name',        foreground: 'c084fc' },
    { token: 'attribute.name.html',   foreground: 'c084fc' },

    { token: 'attribute.value',       foreground: 'a8e06a' },
    { token: 'attribute.value.html',  foreground: 'a8e06a' },
    { token: 'string',                foreground: 'a8e06a' },
    { token: 'string.xml',            foreground: 'a8e06a' },

    { token: 'attribute.value.xpath', foreground: 'fbbf24' },

    { token: 'comment',               foreground: '3d5470', fontStyle: 'italic' },
    { token: 'comment.xml',           foreground: '3d5470', fontStyle: 'italic' },

    { token: 'number',                foreground: 'e8c56d' },

    { token: 'entity.xml',            foreground: 'c084fc' },
  ],
  colors: {
    'editor.background':                  '#00000000',
    'editor.foreground':                  '#c8d8e8',
    'editorLineNumber.foreground':        '#1e3050',
    'editorLineNumber.activeForeground':  '#4a70a8',
    'editor.lineHighlightBackground':     '#0c1826',
    'editor.lineHighlightBorderColor':    '#182030',
    'editorCursor.foreground':            '#0070f2',
    'editor.selectionBackground':         '#183060',
    'editor.inactiveSelectionBackground': '#10203a',
    'editorIndentGuide.background1':      '#182030',
    'editorIndentGuide.background2':      '#182030',
    'editorIndentGuide.background3':      '#182030',
    'editorIndentGuide.background4':      '#182030',
    'editorIndentGuide.background5':      '#182030',
    'editorIndentGuide.background6':      '#182030',
    'editorIndentGuide.activeBackground1':'#1e3050',
    'editorIndentGuide.activeBackground2':'#1e3050',
    'editorIndentGuide.activeBackground3':'#1e3050',
    'editorIndentGuide.activeBackground4':'#1e3050',
    'editorIndentGuide.activeBackground5':'#1e3050',
    'editorIndentGuide.activeBackground6':'#1e3050',
    'editorBracketHighlight.foreground1': '#2e6db4',
    'editorBracketHighlight.foreground2': '#2e8b4a',
    'editorBracketHighlight.foreground3': '#b47a2e',
    'editorBracketHighlight.foreground4': '#7a2eb4',
    'editorBracketHighlight.foreground5': '#2eb4b4',
    'editorBracketHighlight.foreground6': '#b42e5a',
    'scrollbarSlider.background':         '#182030aa',
    'scrollbarSlider.hoverBackground':    '#1e3050aa',
    'editorWidget.background':            '#0d1420',
    'input.background':                   '#0a1020',
    'dropdown.background':                '#0d1420',
  }
};

var MONACO_THEME_LIGHT = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'tag',                   foreground: '0550ae', fontStyle: 'bold' },
    { token: 'tag.id.pug',            foreground: '0550ae' },
    { token: 'attribute.name',        foreground: '116329' },
    { token: 'attribute.name.html',   foreground: '116329' },
    { token: 'attribute.value',       foreground: '0a3069' },
    { token: 'attribute.value.html',  foreground: '0a3069' },
    { token: 'attribute.value.xpath', foreground: 'b45309' },
    { token: 'string',                foreground: '0a3069' },
    { token: 'string.xml',            foreground: '0a3069' },
    { token: 'delimiter.xml',         foreground: '8090a0' },
    { token: 'metatag.xml',           foreground: 'a626a4' },
    { token: 'comment',               foreground: '6a737d', fontStyle: 'italic' },
    { token: 'comment.xml',           foreground: '6a737d', fontStyle: 'italic' },
    { token: 'number',                foreground: 'b5521a' },
    { token: 'entity.xml',            foreground: '6f42c1' },
  ],
  colors: {
    'editor.background':                  '#00000000',
    'editor.foreground':                  '#1a2535',
    'editorLineNumber.foreground':        '#c0cfe0',
    'editorLineNumber.activeForeground':  '#6080a0',
    'editor.lineHighlightBackground':     '#f0f6ff',
    'editor.lineHighlightBorderColor':    '#d8e8f8',
    'editorCursor.foreground':            '#0070f2',
    'editor.selectionBackground':         '#b8d4f8',
    'editor.inactiveSelectionBackground': '#d8e8f8',
    'editorIndentGuide.background1':      '#e0e8f0',
    'editorIndentGuide.background2':      '#e0e8f0',
    'editorIndentGuide.background3':      '#e0e8f0',
    'editorIndentGuide.background4':      '#e0e8f0',
    'editorIndentGuide.background5':      '#e0e8f0',
    'editorIndentGuide.background6':      '#e0e8f0',
    'editorIndentGuide.activeBackground1':'#b0c4d8',
    'editorIndentGuide.activeBackground2':'#b0c4d8',
    'editorIndentGuide.activeBackground3':'#b0c4d8',
    'editorIndentGuide.activeBackground4':'#b0c4d8',
    'editorIndentGuide.activeBackground5':'#b0c4d8',
    'editorIndentGuide.activeBackground6':'#b0c4d8',
    'editorBracketHighlight.foreground1': '#2e6db4',
    'editorBracketHighlight.foreground2': '#1a7f37',
    'editorBracketHighlight.foreground3': '#c87800',
    'editorBracketHighlight.foreground4': '#6f42c1',
    'editorBracketHighlight.foreground5': '#0969a0',
    'editorBracketHighlight.foreground6': '#cf222e',
    'scrollbarSlider.background':         '#c0cfe0aa',
    'scrollbarSlider.hoverBackground':    '#a8bcd4aa',
    'editorWidget.background':            '#f0f4f8',
    'input.background':                   '#ffffff',
    'dropdown.background':                '#f0f4f8',
  }
};
